version: '3.8'

services:
  # Servicio de nuestra aplicación
  frontend:
    build: ./frontend # Construye desde la carpeta frontend
    container_name: bootcamp-frontend
    ports:
      - "80:80" # Expone el puerto 80 del Nginx al 80 de tu máquina
    depends_on:
      - app
  app:
    build: .
    container_name: bootcamp-app
    # ports: <- COMENTA O ELIMINA ESTA LÍNEA, AHORA SE ACCEDE A TRAVÉS DE NGINX
    #  - "5000:5000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
    depends_on:
      - db

  # Servicio de la base de datos
  db:
    # Usamos una imagen ligera de Postgres (basada en Alpine Linux)
    image: postgres:14-alpine
    container_name: bootcamp-db
    # Estas variables son usadas por la imagen de Postgres para inicializar la BD
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # Monta un volumen para que los datos de la base de datos persistan
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Opcional: para conectar a la BD desde tu máquina local con una herramienta como DBeaver
    ports:
      - "5432:5432"

# Docker gestionará la creación y el ciclo de vida de este volumen
volumes:
  postgres_data: