# La directiva 'version' es opcional en las versiones modernas de Docker Compose
# version: '3.8'

services:
  # --- SERVICIOS DE LA APLICACIÓN ---
  frontend:
    build: ./frontend
    container_name: bootcamp-frontend
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build: .
    container_name: bootcamp-app
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: bootcamp-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: # Opcional: para conectar a la BD directamente desde tu máquina
      - "5432:5432"

  # --- SERVICIOS DE MONITOREO ---
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: bootcamp-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - app

  grafana:
    image: grafana/grafana:9.5.1
    container_name: bootcamp-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

# --- DECLARACIÓN DE VOLÚMENES PERSISTENTES ---
# Esta sección debe estar al final y sin indentación
volumes:
  postgres_data:
  grafana_data: